
export const FETCH_PRODUCT_REQUEST="FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE="FETCH_PRODUCT_FAILURE";
export const FETCH_CART_FAILURE="FETCH_CART_FAILURE";
export const FETCH_CART_REQUEST="FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS";